# basic options
title: Game Development blog 
author: Mindengine76
email: JC206631@falmouth.ac.uk
description: A wonderful story
github_username: Mindengine76

#Build settings
markdown: 
theme: minima
