# basic options
title: Your awesome title
author: github user
email: your awesome email -email@domain.com
description: A wonderful story
github_username: jekyll

#Build settings
markdown: kramdon
theme: minima
